baseURL = "https://akashsara.github.io/"
languageCode = "en-us"
title = "Akash Saravanan "
theme = "avicenna"
googleAnalytics = "UA-137697069-1"
timeout=3000
publidhDir = "public"

[params]
  subtitle= "Machine Learning Scientist"
  interests="Artificial Intelligence (AI) for Games, Natural Language Processing (NLP), Large Language Models (LLMs)."
  cv_name= "Akash_Saravanan_CV.pdf"
  # blog="http://myblog.edu"

[[params.affilation]]
  name = "Georgian"
  position = "Machine Learning Scientist"
  contact = "akashsara@outlook.com"
    
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/akashsara"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/akashsara"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/akashsara/"


[[params.introduction.paragraph]]
  text="""Hello there! I’m Akash, a problem solver specializing in machine learning.

  My current work revolves around leveraging Large Language Models (LLMs) and Natural Language Processing (NLP) techniques, including Retrieval Augmented Generation (RAG), fine-tuning, and advanced prompting strategies. Over the years, I’ve explored a wide range of fields, such as graph machine learning, computer vision, representation learning, and reinforcement learning, applying these skills across industries like insurance, retail, education, healthcare, manufacturing, human resources, video games, and blockchain.

  With hands-on experience in Python (and some JavaScript), I’m adept with frameworks like PyTorch, Tensorflow and scikit-learn, and cloud services such as AWS and GCP. I’m equally comfortable with different database systems — SQL, NoSQL, and vector databases. If you're curious about specific projects I’ve worked on, feel free to check out my resume linked on this page and/or send me a message on LinkedIn.

  Outside of machine learning, I’m passionate about football (soccer), fantasy/sci-fi media, and random trivia. I love sharing recommendations, so: The Stormlight Archive (book series), The Talos Principle 2 (video game), Delicious in Dungeon (anime), Game Changer (game show), and Bullet Train (movie) are some recent highlights.

  Let’s connect if you’re interested in collaborating, or if you know of exciting opportunities — I’m actively looking for new roles and ready to tackle unique challenges!
  """