baseURL = "https://akashsara.github.io/"
languageCode = "en-us"
title = "Akash Saravanan "
theme = "avicenna"
googleAnalytics = "UA-137697069-1"
timeout=3000
publidhDir = "public"

[params]
  subtitle= "Machine Learning Scientist"
  interests="Artificial Intelligence (AI) for Games, Natural Language Processing (NLP), Large Language Models (LLMs)."
  cv_name= "Akash_Saravanan_CV.pdf"
  # blog="http://myblog.edu"

[[params.affilation]]
  name = "Georgian"
  position = "Machine Learning Scientist"
  contact = "akashsara@outlook.com"
    
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/akashsara"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/akashsara"


[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://linkedin.com/in/akashsara/"


[[params.introduction.paragraph]]
  text="""Hello there, I'm Akash. I work on applied machine learning problems. Currently, this centers around LLMs and NLP, specifically, solving problems using a mixture of RAG, Fine-Tuning, Prompting, and Alignment (RLHF). In the past, I have worked on other areas including computer vision, representation learning, reinforcement learning, and graph machine learning problems. 
  
  My work has spanned across different domains including insurance, retail, video games, and blockchain. Within these domains, I have worked on problems including entity extraction, chatbots, classification, summarization, image generation, video game simulations, regression, and graph analytics. As a result of this broad experience, I'm comfortable with most machine learning frameworks (such as PyTorch and Tensorflow), multiple cloud platforms (AWS and GCP), and several types of databases (including SQL, NoSQL, and vector databases). For more specific information, refer to my resume linked on this page.
  
   Just so that this page isn't purely tech stuff: I enjoy football (or soccer to some folks), trivia, and fantasy/sci-fi media including books, video games, movies, TV, anime, and manga. In the spirit of fun, here are some recommendations for each of those that I've consumed in the last year or so - Red Rising, The Talos Principle 2, Palm Springs, Scavengers Reign, Vinland Saga, and One Piece. 
  
  I'm passionate about solving interesting problems in underexplored domains. Please reach out to me if you want to chat!
  """