name: Build and Deploy
on:
  push:
    branches:
    - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.3
      with:
        hugo-version: '0.59.1'
        extended: true
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        
    - name: Build
      run: hugo -D --verboseLog

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./public